/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package algorithms_2025336;

import java.time.LocalDate;     // Import LocalDate for handling best before dates.
import java.util.ArrayList;

/**
 *
 * @author Dorjragchaa Chuluunbaatar
 */
public class RestaurantStorageGUI extends javax.swing.JFrame {
    
    private final StorageUnit storage;
        
    public RestaurantStorageGUI() {
        storage = new StorageUnit(StorageMode.QUEUE);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Fast-Food Storage Application");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        foodTypeCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        weightField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        CountButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        search = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        peekButton = new javax.swing.JButton();
        modeCombo = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Food Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 204))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Food Type:");
        jPanel1.add(jLabel1);

        foodTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burger", "Pizza", "Fries", "Sandwich", "Hotdog" }));
        foodTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodTypeComboActionPerformed(evt);
            }
        });
        jPanel1.add(foodTypeCombo);

        jLabel2.setText("Weight (grams):");
        jPanel1.add(jLabel2);
        jPanel1.add(weightField);

        jLabel3.setText("Best Before (YYYY-MM-DD):");
        jPanel1.add(jLabel3);
        jPanel1.add(dateField);

        removeButton.setText("Remove Food");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add Food");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        CountButton.setText("Count item");
        CountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Storage Contents", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 204))); // NOI18N

        displayArea.setColumns(20);
        displayArea.setRows(5);
        jScrollPane1.setViewportView(displayArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        displayButton.setText("Display All");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        peekButton.setText("Peek Top");
        peekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peekButtonActionPerformed(evt);
            }
        });

        modeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUEUE", "STACK" }));

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Search Food Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(modeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(CountButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(peekButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(displayButton))
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(13, 13, 13))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(removeButton)
                .addGap(83, 83, 83)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayButton)
                    .addComponent(CountButton)
                    .addComponent(peekButton)
                    .addComponent(exitButton))
                .addGap(35, 35, 35))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Add Food Details");
        jPanel2.getAccessibleContext().setAccessibleName("Display");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private FoodItem createFoodItem(String selectedFood, int weight, LocalDate bestBeforeDate) {
    switch (selectedFood) {
        case "Burger":
            return new Burger(weight, bestBeforeDate);
        case "Pizza":
            return new Pizza(weight, bestBeforeDate);
        case "Fries":
            return new Fries(weight, bestBeforeDate);
        case "Sandwich":
            return new Sandwich(weight, bestBeforeDate);
        case "Hotdog":
            return new Hotdog(weight, bestBeforeDate);
        default:
            throw new IllegalArgumentException("Invalid food type selected.");
    }
}
    
    private void displayCurrentFoods() {
    displayArea.append("Current Food Items in Storage:\n");

    java.util.List<FoodItem> foods = storage.displayItems();

    if (foods.isEmpty()) {
        displayArea.append("Storage is empty.\n");
    } else {
        int i = 1;
        for (FoodItem food : foods) {
            displayArea.append(i + ". " + food.toString() + "\n");
            i++;
        }
    }

    displayArea.append("-----------------------------------\n");
}
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

            try {
                String selectedFood = foodTypeCombo.getSelectedItem().toString();
                int weight = Integer.parseInt(weightField.getText().trim());
                LocalDate bestBeforeDate = LocalDate.parse(dateField.getText().trim());

                String selectedMode = modeCombo.getSelectedItem().toString();
                if (selectedMode.equals("STACK")) {
                    storage.setMode(StorageMode.STACK);
                } else {
                    storage.setMode(StorageMode.QUEUE);
                }

                FoodItem food = createFoodItem(selectedFood, weight, bestBeforeDate);
                storage.addItem(food);

                displayArea.append(food.toString() + " has been added to storage.\n");
                displayArea.append("Current mode: " + storage.getMode() + "\n");

                if (!storage.isEmpty()) {
                    displayArea.append("Top item: " + storage.peekItem().toString() + "\n");
                }

                displayArea.append("-----------------------------------\n");
                displayCurrentFoods();

                weightField.setText("");
                dateField.setText("");

            } catch (NumberFormatException e) {
                displayArea.append("Weight must be a valid integer.\n\n");
            } catch (java.time.format.DateTimeParseException e) {
                displayArea.append("Date must be in YYYY-MM-DD format.\n\n");
            } catch (Exception e) {
                displayArea.append(e.getMessage() + "\n\n");
            }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

            try {
                FoodItem removedFood = storage.removeItem();
                displayArea.append("Removed: " + removedFood.getName() + "\n");

                if (!storage.isEmpty()) {
                    displayArea.append("Top item now: " + storage.peekItem().toString() + "\n");
                } else {
                    displayArea.append("Storage is now empty.\n");
                }

                displayArea.append("-----------------------------------\n");
                displayCurrentFoods();

            } catch (Exception e) {
                displayArea.append(e.getMessage() + "\n\n");
            }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);     // Click the "Exit" button to close the program.
    }//GEN-LAST:event_exitButtonActionPerformed

    private void CountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountButtonActionPerformed

    displayArea.append("There are " + storage.size() + " food items in storage.\n");
    displayArea.append("Current mode: " + storage.getMode() + "\n");
    displayArea.append("-----------------------------------\n");
    }//GEN-LAST:event_CountButtonActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        try {
            String searchName = searchField.getText().trim();
            FoodItem foundFood = storage.searchItem(searchName);

            if (foundFood != null) {
                displayArea.append("Search Result:\n");
                displayArea.append(foundFood.toString() + "\n");
            } else {
                displayArea.append("No food item found with name: " + searchName + "\n");
            }

            displayArea.append("-----------------------------------\n");
        } catch (Exception e) {
            displayArea.append(e.getMessage() + "\n\n");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void peekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peekButtonActionPerformed

            try {
                FoodItem topFood = storage.peekItem();
                displayArea.append("Top / Front Food Item:\n");
                displayArea.append(topFood.toString() + "\n");
                displayArea.append("-----------------------------------\n");
            } catch (Exception e) {
                displayArea.append(e.getMessage() + "\n\n");
            }
    }//GEN-LAST:event_peekButtonActionPerformed

    private void foodTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodTypeComboActionPerformed

    }//GEN-LAST:event_foodTypeComboActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        displayCurrentFoods();
    }//GEN-LAST:event_displayButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantStorageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantStorageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantStorageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantStorageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantStorageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CountButton;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JButton displayButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox<String> foodTypeCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> modeCombo;
    private javax.swing.JButton peekButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
// GUI class for managing restaurant food storage with Stack and Queue modes